#!/bin/bash
# This script takes one argument: the six digit MFA code from your AWS authenticator.
# It will then update the ~/.config/bash/aws.env file with the necessary values.
# Finally, it will source the new values, so you should be ready to go in the current shell.

# Get the session information
info=`aws sts get-session-token --serial-number $AWS_MFA_SERIAL_NUMBER --token-code $1`
access_key=`echo $info | jq -r ".Credentials" | jq -r ".AccessKeyId"`
secret_access_key=`echo $info | jq -r ".Credentials" | jq -r ".SecretAccessKey"`
session_token=`echo $info | jq -r ".Credentials" | jq -r ".SessionToken"`
expiration=`echo $info | jq -r ".Credentials" | jq -r ".Expiration"`

file=~/.config/bash/aws-session.env

# Remove any old session
rm -f $file

# Create the new file
echo "export AWS_ACCESS_KEY_ID=$access_key\n" >> $file
echo "export AWS_SECRET_ACCESS_KEY_ID=$secret_access_key\n" >> $file
echo "export AWS_SESSION_TOKEN=$session_token\n" >> $file
echo "echo 'AWS credentials expire at $expiration'" >> $file

# Use the new credentials
source $file
